Support TLS
joomcode/redispipe pull request #24
Opened 2023-02-24 16:33 UTC by aglarendil

Allow to pass TLSEnabled bool and TLSConfig struct to opts thus effectively enabling TLS Support.

2023-02-28 10:43 UTC, marusama requested changes

2023-02-28 10:43 UTC, marusama commented on rediscluster/cluster.go
> +	TLSConfig         tls.Config
тут нужно по указателю, потому что tls.Config содержит RWMutex:
```
github.com/joomcode/redispipe/redisconn.Opts contains crypto/tls.Config contains sync.RWMutex (copylocks)
```

2023-02-28 10:43 UTC, marusama commented on redisconn/conn.go
> +	TLSConfig  tls.Config
тут тоже нужен указатель

2023-02-28 14:26 UTC, marusama approved these changes

2023-03-02 08:11 UTC, g7r approved these changes

2023-03-02 14:59 UTC, merged