add possibility to set replica weights explicitly
joomcode/redispipe pull request #28
Opened 2023-05-18 08:41 UTC by Sovianum

Добавляю возможность снаружи проставить веса репликам во всех шардах

2023-05-24 08:56 UTC, g7r requested changes

2023-05-24 10:49 UTC, Sovianum commented on rediscluster/cluster.go
> +	WeightsByAddress map[string]uint32
Added fallback to default strategy in case of weight incompleteness

2023-05-24 11:46 UTC, Sovianum commented on rediscluster/cluster.go
> +	WeightsByAddress map[string]uint32
Switched to interface instead of map

2023-05-25 07:27 UTC, g7r requested changes

2023-05-25 07:37 UTC, Sovianum commented on rediscluster/cluster.go
> +	GetWeightsByHost(hosts []string) ([]uint32, []bool)
Fixed

2023-05-25 07:41 UTC, Sovianum commented on rediscluster/cluster.go
> +type WeightProvider interface {
Fixed

2023-05-25 08:09 UTC, g7r approved these changes

2023-05-25 08:10 UTC, merged